const products=[
    {id:"1",
    title:"Motosierra Huqsvarna", 
    tipo:"Motosierras",
    price:2000, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054577/motosierra2_dx0eag.jpg",
    
    },
    {id:"2",
    title:"Motosierra Sthil", 
    tipo:"Motosierras",
    price:2200, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054576/motosierra3_xvjkpr.jpg",
    },
    {id:"3",
    title:"Motosierra Hyundai", 
    tipo:"Motosierras",
    price:2300, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054577/motosierra1_xq3eja.jpg",
    },
    {id:"4",
    title:"Taladro INCCO 20V", 
    tipo:"Taladros",
    price:1500, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054577/taladro4_e8cvpu.jpg",
    },
    {id:"5",
    title:"Taladro Total 20V", 
    tipo:"Taladros",
    price:1450, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054576/taladro2_jvhebz.jpg",
    },
    {id:"6",
    title:"Taladro de 12V", 
    tipo:"Taladros",
    price:1300, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054576/taladro3_xrroig.jpg",
    },
    {id:"7",
    title:"Taladro CAT 12V", 
    tipo:"Taladros",
    price:1400, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054576/taladro1_ml2wse.jpg",
    },
    {id:"8",
    title:"Amoladora", 
    tipo:"Otros",
    price:1300, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054576/amoladora3_hjbmbg.jpg",
    },
    {id:"9",
    title:"Sierra automatica Skul", 
    tipo:"Otros",
    price:1500, 
    imgurl:"https://res.cloudinary.com/dob4gyxkv/image/upload/v1674054576/sierra_fjhqv3.jpg",
    },
];

export default products;